#index:
controllers:
    resource: '../src/Controller/'
    type:     annotation
index:
    path: /
    controller: App\Controller\DefaultController::index

#FirebaseController
loadUserFriendList:
    path: user/loadfriendlist/id={userId}
    controller : App\Controller\UserDatabaseController::loadFriendList
    defaults:
        userId: "No user Id"
loadPokemonList:
    path: /user/userid={userId}/pokemonlist
    controller: App\Controller\UserDatabaseController::loadPokemonCollection
    defaults:
        userId: "No user Id"
getUserData:
    path: /user/userid={userId}/getuserdata/
    controller: App\Controller\UserDatabaseController::getUserData
    defaults:
        userId: "No user Id"
initUser:
    path: user/userid={userId}/init
    controller: App\Controller\UserDatabaseController::initUser
    defaults:
        userId: "No user Id"
        username: "No username"
        avatarImage: "No avatar url"
        email: "No email"
addPokemonToFirebase:
    path: /user/userid={userId}/addpokemontocollection/id={pokemonId}/nickname={nickname}/creationdate={creationDate}
    controller: App\Controller\PokemonController::addPokemonToFirebase
    defaults:
        userId : "No user Id"
        pokemonId : 0
        nickname : ""
        creationDate : ""
sendPokemonToProfChen:
    path: /user/userid={userId}/sendpokemontochen/pokemonid={pokemonId}
    controller: App\Controller\ExchangesController::sendPokemonToProfChen
    defaults:
        pokemonId: 0
        userId: "No user Id"
getPokemonById:
    path: /user/userid={userId}/pokemon/loadpokemonbyid/id={pokemonId}
    controller: App\Controller\ExchangesController::loadPokemonById
    defaults:
        userId: ""
        pokemonId: 0
#PokemonController
loadTypes:
    path: /types/all
    controller: App\Controller\PokemonController::loadTypes
craftPokemon:
    path: user/userid={userId}/craft/pokemon/firstypeid={firstTypeId}/secondtypeid={secondTypeId}
    controller: App\Controller\PokemonController::craftPokemon
    defaults:
        firstTypeId: 0
        secondTypeId: 0
        userId: ""
fetchList:
    path: /pokemon/list/pageid={pageId}
    controller: App\Controller\PokemonController::fetchPokedexPage
    defaults:
        pageId: 0
pokemonBasicInfos:
    path: /pokemon/rendbasicinfos/pokemonid={id}
    controller: App\Controller\PokemonController::renderPokemonBasicInformations
    defaults:
        id: 0
disolvingPokemon:
    path: /users/{userId}/disolving/pokemonId={pokemonId}/pokemonIdCrafted={pokemonCraftedId}
    controller: App\Controller\PokemonController::renderPokemonBasicInformations
    defaults:
        userId : "No user Id"
        pokemonId : 0
        pokemonCraftedId : ""
#MarketExchanges
addPokemonToMarket:
    path : /exchanges/userid={userId}/addpokemontomarket/originalPokemonId={originalPokemonId}/pokemonidwanted={pokemonIdWanted}
    controller: App\Controller\ExchangesController::addPokemonToExchangeMarket
    defaults:
        pokemonIdWanted: 0
        originalPokemonId: 0
        pokemonIdWantedCraftedId: "No id"
        originalPokemonIdCrafted: "No id"
        userId: "No user Id"
listTrades:
    path: /trades/list/
    controller: App\Controller\ExchangesController::listTradeExchanges
confirmExchange:
    path: /trades/confirm/userid={userId}/originalpokemonid={originalPokemonId}/frienduserid={friendUserId}/pokemonidwanted={pokemonIdWanted}
    controller: App\Controller\ExchangesController::confirmExchange
    defaults:
        pokemonIdWanted: 0
        originalPokemonId: 0
        userId: "No user Id"
        friendUserId: "No user Id"