#index:
controllers:
    resource: '../src/Controller/'
    type:     annotation
index:
    path: /
    controller: App\Controller\DefaultController::index

#FirebaseController
loadUserFriendList:
    path: /loadUserFriendList/{userId}
    controller : App\Controller\UserDatabaseController::loadFriendList
    defaults:
        userId: "No user Id"
loadPokemonList:
    path: /users/{userId}/pokemonList
    controller: App\Controller\UserDatabaseController::loadPokemonCollection
    defaults:
        userId: "No user Id"

#PokemonController
loadTypes:
    path: /types/all
    controller: App\Controller\PokemonController::loadTypes
craftPokemon:
    path: /craft/pokemon/{firstTypeId}/{secondTypeId}
    controller: App\Controller\PokemonController::craftPokemon
    defaults:
        firstTypeId: 0
        secondTypeId: 0
fetchList:
    path: /pokemonlist/{pageId}
    controller: App\Controller\PokemonController::fetchPokedexPage
    defaults:
        pageId: 0
pokemonBasicInfos:
    path: /pokemon/{id}
    controller: App\Controller\PokemonController::renderPokemonBasicInformations
    defaults:
        id: 0
disolvingPokemon:
    path: /users/{userId}/disolving/{pokemonId}/{pokemonCraftedId}
    controller: App\Controller\PokemonController::renderPokemonBasicInformations
    defaults:
        userId : "No user Id"
        pokemonId : 0
        pokemonCraftedId : ""
#MarketExchanges
addPokemonToMarket:
    path : /exchanges/{userId}/{originalPokemonId}/{friendUserId}/{pokemonIdWanted}
    controller: App\Controller\ExchangesController::addPokemonToExchangeMarket
    defaults:
        pokemonIdWanted: 0
        originalPokemonId: 0
        pokemonIdWantedCraftedId: ""
        originalPokemonIdCrafted: ""
        userId: "No user Id"
        friendUserId: "No user Id"
confirmExchange:
    path: /exchanges/confirm/{userId}/{originalPokemonId}/{originalCraftedPokemonId}/{friendUserId}/{pokemonIdWanted}/{pokemonCraftedIdWanted}
    controller: App\Controller\ExchangesController::confirmExchange
    defaults:
        pokemonIdWanted: 0
        originalPokemonId: 0
        userId: "No user Id"
        friendUserId: "No user Id"
        originalCraftedPokemonId: ""
        pokemonCraftedIdWanted: ""
sendPokemonToProfChen:
    path: /users/{userId}/sendpokemontochen/{pokemonId}/{pokemonCraftedId}
    controller: App\Controller\ExchangesController::sendPokemonToProfChen
    defaults:
        pokemonId: 0
        userId: "No user Id"
        pokemonCraftedId: ""