#index:
controllers:
    resource: '../src/Controller/'
    type:     annotation
index:
    path: /
    controller: App\Controller\DefaultController::index
loadingData:
    path: /loadingData/{id}
    controller : App\Controller\FirebaseController::insert
    defaults:
        id: 0
