#index:
controllers:
    resource: '../src/Controller/'
    type:     annotation
index:
    path: /
    controller: App\Controller\DefaultController::index

#FirebaseController
loadUserFriendList:
    path: /loadUserFriendList/{userId}
    controller : App\Controller\UserDatabaseController::loadFriendList
    defaults:
        userId: "No user Id"
fetchList:
    path: /pokemonlist/{pageId}
    controller: App\Controller\PokemonController::fetchPokedexPage
    defaults:
        pageId: 0
#PokemonController
loadPokemonList:
    path: /users/{userId}/pokemonList
    controller: App\Controller\UserDatabaseController::loadPokemonCollection
    default:
        userId: "No user Id"
loadTypes:
    path: /types/all
    controller: App\Controller\PokemonController::loadTypes
craftPokemon:
    path: /craft/pokemon/{firstTypeId}/{secondTypeId}
    controller: App\Controller\PokemonController::craftPokemon
    defaults:
        firstTypeId: 0
        secondTypeId: 0