#index:
controllers:
    resource: '../src/Controller/'
    type:     annotation
index:
    path: /
    controller: App\Controller\DefaultController::index
pokemonBasicInfos:
    path: /pokemon/{id}
    controller: App\Controller\PokemonController::renderPokemonBasicInformations
    defaults:
        id: 0
fetchList:
    path: /pokemonlist/{pageId}
    controller: App\Controller\PokemonController::fetchPokedexPage
    defaults:
        pageId: 0
loadTypes:
    path: /types/all
    controller: App\Controller\PokemonController::loadTypes