#index:
controllers:
    resource: '../src/Controller/'
    type:     annotation
index:
    path: /
    controller: App\Controller\DefaultController::index
pokemonBasicInfos:
    path: /pokemon/{id}
    controller: App\Controller\PokemonController::renderPokemonBasicInformations
    defaults:
        id: 0
pokemonList:
    path: /pokemonList/{pageId}
    controller: App\Controller\PokemonController::renderPokemonList
    defaults:
        url: 0
