#index:
controllers:
    resource: '../src/Controller/'
    type:     annotation
index:
    path: /
    controller: App\Controller\DefaultController::index

#FirebaseController
loadUserFriendList:
    path: /loadUserFriendList/{userId}
    controller : App\Controller\UserDatabaseController::loadFriendList
    defaults:
        userId: "No user Id"
loadPokemonList:
    path: /users/{userId}/pokemonList
    controller: App\Controller\UserDatabaseController::loadPokemonCollection
    defaults:
        userId: "No user Id"
getUserData:
    path: /userData/{userId}
    controller: App\Controller\UserDatabaseController::getUserData
    defaults:
        userId: "No user Id"
initUser:
    path: /{userId}/init
    controller: App\Controller\UserDatabaseController::initUser
    defaults:
        userId: "No user Id"
        username: "No username"
        avatarImage: "No avatar url"
        email: "No email"
#PokemonController
loadTypes:
    path: /types/all
    controller: App\Controller\PokemonController::loadTypes
craftPokemon:
    path: users/{userId}/craft/pokemon/{firstTypeId}/{secondTypeId}
    controller: App\Controller\PokemonController::craftPokemon
    defaults:
        firstTypeId: 0
        secondTypeId: 0
        userId: ""
fetchList:
    path: /pokemonlist/{pageId}
    controller: App\Controller\PokemonController::fetchPokedexPage
    defaults:
        pageId: 0
pokemonBasicInfos:
    path: /pokemon/{id}
    controller: App\Controller\PokemonController::renderPokemonBasicInformations
    defaults:
        id: 0
disolvingPokemon:
    path: /users/{userId}/disolving/{pokemonId}/{pokemonCraftedId}
    controller: App\Controller\PokemonController::renderPokemonBasicInformations
    defaults:
        userId : "No user Id"
        pokemonId : 0
        pokemonCraftedId : ""
addPokemonToFirebase:
    path: /users/{userId}/add/{pokemonId}/{nickname}/{creationDate}
    controller: App\Controller\PokemonController::addPokemonToFirebase
    defaults:
        userId : "No user Id"
        pokemonId : 0
        nickname : ""
        creationDate : ""
#MarketExchanges
addPokemonToMarket:
    path : /exchanges/{userId}/{originalPokemonId}/{pokemonIdWanted}
    controller: App\Controller\ExchangesController::addPokemonToExchangeMarket
    defaults:
        pokemonIdWanted: 0
        originalPokemonId: 0
        pokemonIdWantedCraftedId: "No id"
        originalPokemonIdCrafted: "No id"
        userId: "No user Id"
listTrades:
    path: /list/exchanges
    controller: App\Controller\ExchangesController::listTradeExchanges
confirmExchange:
    path: /exchanges/confirm/{userId}/{originalPokemonId}/{friendUserId}/{pokemonIdWanted}
    controller: App\Controller\ExchangesController::confirmExchange
    defaults:
        pokemonIdWanted: 0
        originalPokemonId: 0
        userId: "No user Id"
        friendUserId: "No user Id"
        tradeId: -1
sendPokemonToProfChen:
    path: /users/{userId}/sendpokemontochen/{pokemonId}
    controller: App\Controller\ExchangesController::sendPokemonToProfChen
    defaults:
        pokemonId: 0
        userId: "No user Id"
getPokemonById:
    path: /user/{userId}/pokemon/{pokemonId}
    controller: App\Controller\ExchangesController::loadPokemonById
    defaults:
        userId: ""
        pokemonId: 0