#index:
controllers:
    resource: '../src/Controller/'
    type:     annotation
index:
    path: /
    controller: App\Controller\DefaultController::index
pokemonBasicInfos:
    path: /pokemon/{id}
    controller: App\Controller\PokemonController::renderPokemonBasicInformations
getPokemonList:
    path: /pokemonList/{begin}
    controller: App\Controller\PokemonController::renderPokemonBasicList
